### PR TITLE
Bandaid fix of Tiny-Kafka example

### PR DESCRIPTION
**Pull request by RothAndrew**
Related to #41

### CODE REVIEW

**Comment by RothAndrew** [comment]
@jeff-mccoy are you good with merging this as a bandaid fix until the deeper issue is resolved?

**Comment by jeff-mccoy** [comment]
It's a clever work-around, but let me see if I can fix it in the CLI today first if you don't mind

**Comment by RothAndrew** [comment]
sure.

**Comment by jeff-mccoy** [comment]
Closed in favor of #45

**Pull request closed without merging**
