### PR TITLE
Feature/restructure zarf config yaml

### LINKED ISSUE #64: Expanding Zarf Features to regular zarf packages
### Discussed in https://github.com/defenseunicorns/zarf/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **jeff-mccoy** September 24, 2021</sup>
Currently only `zarf-init` has the ability to deploy what is in the zarf package and optional additional groups of assets called features.  Providing this capability to regular zarf packages as well wouldn't be difficult, but would allow greater flexibility with package creation.  The only issue would be needing to resolve the use of `local` vs `remote` in the zarf config, https://github.com/defenseunicorns/zarf/discussions/40#discussioncomment-1381213.

Example usage in [zarf init yaml](https://github.com/defenseunicorns/zarf/blob/master/zarf.yaml)
```yaml
features:
  - name: management
    description: "Add the K9s terminal-based K8s UI for cluster management"
    default: true
    files:
      - source: https://zarf-public.s3-us-gov-west-1.amazonaws.com/k9s_Linux_x86_64_v0_24_11
        shasum: 18a5a33bbf58cb228e56a03380dcb6b9bb8624acab4ff63deb7364dc15d3c03f
        target: "/usr/local/bin/k9s"
        executable: true
      - source: assets/misc/k9s-theme.yaml
        target: "/root/.k9s/skin.yml"
```

How this would look for an example package, [tiny-kafka](https://github.com/defenseunicorns/zarf/blob/master/examples/tiny-kafka/zarf.yaml)
```yaml
kind: ZarfPackageConfig
metadata:
  name: kafka-strimzi-demo
  description: "Demo tiny Zarf Kafka deployment"
  
local:
  manifests: manifests

  charts:
    - name: strimzi-kafka-operator
      url: https://strimzi.io/charts/
      version: 0.24.0

  images:
    - registry1.dso.mil/ironbank/opensource/strimzi/operator:0.24.0
    - registry1.dso.mil/ironbank/opensource/strimzi/kafka:0.24.0-kafka-2.8.0

features:
  - name: kafka-tools
    description: "Add useful tools to manage Kafka"
    default: true
    files:
      # Helper tools for working with kafka
      - source: https://archive.apache.org/dist/kafka/2.8.0/kafka_2.13-2.8.0.tgz
        shasum: 3fa380ae5d1385111ee9c83b0d1806172924ffec2e29399fd1a42671a97492c6
        target: /opt/kafka.tgz
```</div>

### PR DESCRIPTION
**Pull request by jeff-mccoy**
Closes #64 and helps cleanup https://github.com/defenseunicorns/zarf/discussions/40#discussion-3575111

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Passing build and E2E:  https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/pipelines/508564

**Comment by RothAndrew** [comment]
Good stuff. Taking a look now.

**Comment by RothAndrew** [comment]
Update: haven't even had a chance to look at this yet. Meetings are blowing up my day. The code all looks fine to me, I did want to deploy each example to make sure none of them were broken.

**Comment by RothAndrew** [comment]
Okay pinky swear I'm actually looking now

**Comment by RothAndrew** [comment]
@jeff-mccoy can you try the big bang example? I think the utility cluster stuff isn't working, want to make sure it isn't just a "me" thing

**Comment by RothAndrew** [comment]
image

The command finishes waaaay faster than it used to, and I don't see any repos in gitea

image

**Comment by jeff-mccoy** [comment]
It did feel too easy, I’ll check it out

**Comment by RothAndrew** [comment]
It looks like `zarf package deploy` is missing the `--components` flag. Want to add it here or do it in a new PR? I'm fine with either.

**Comment by RothAndrew** [comment]
image

**Comment by jeff-mccoy** [comment]
Good catch, I’ll get that in this pr too later this evening

**Comment by RothAndrew** [comment]
LGTM other than the `--components` flag being missing

**Comment by jeff-mccoy** [comment]
Screen Shot 2021-10-03 at 2 18 55 AM

Screen Shot 2021-10-03 at 2 16 37 AM

Screen Shot 2021-10-03 at 2 16 47 AM

**Review by RothAndrew — APPROVED** [review]

**Pull request merged**
