### PR TITLE
[TASK] Update when to where in walkthrough docs

### LINKED ISSUE #1658: Small Docs Issue, change when to where
### Environment
Device and OS: MacOS
App version: N/A
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. https://docs.zarf.dev/docs/walkthroughs/deploying-zarf-packages#deploying-the-helm-oci-chart-package 

Change when to where. 

Original
```text
Navigate to the folder when you created the package in a previous walkthrough.
```

Desired Change
```text
Navigate to the folder where you created the package in a previous walkthrough.
```
### Visual Proof (screenshots, videos, text, etc)
https://docs.zarf.dev/docs/walkthroughs/deploying-zarf-packages#deploying-the-helm-oci-chart-package 

image

### Severity/Priority
low

### Additional Context
I am submitting a PR to address this.

### PR DESCRIPTION
**Pull request by cmwylie19**
## Description

Just a small doc correction. Closes #1658 

## Related Issue

Fixes #1658 

Relates to #1658

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Review by Racer159 — COMMENTED** [review]
Looks good to me but there are merge conflicts due to some walkthrough updates that went out today - that error is still on the now helm-oci deployment walkthrough though.  And thanks for the PR!

**Comment by cmwylie19** [comment]
> Looks good to me but there are merge conflicts due to some walkthrough updates that went out today - that error is still on the now helm-oci deployment walkthrough though. And thanks for the PR!

My fault, you are right! Just rebased. My pleasure!

**Review by Racer159 — APPROVED** [review]
Lgtm!

**Review by Noxsios — APPROVED** [review]
lgtm as well 👍

**Pull request merged**
