### PR TITLE
Bug: Fetch release now depends on clean. It fails when the sync folde…

### PR DESCRIPTION
**Pull request by AustinAbro321**
Was going through the zarf big bang example and noticed this! Here is an example of what happens when you try to run the make  fetch-release while the sync folder isn't created. 
zarf_make_fetch_release_error

### CODE REVIEW

**Comment by YrrepNoj** [comment]
@AustinAbro321, thanks for pushing this. I feel like I remember running into this the first time I tried to build and then just forgot about it since I already had the sync directory afterwards.

What do you think about adding `	@mkdir -p sync` in the steps instead of executing the `clean` recipe? I worry that someone might lose all their packages just from trying to make sure they have the latest binary release. To be honest, I'm perfectly fine keeping it like this, just wanted to get your thoughts.

We also are trying to keep the commits in this repo signed and verified. Here are some of GitHubs docs on doing that. Let me know if you have any questions on this because I know these instructions aren't always the most clear. https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by RothAndrew** [comment]
I agree with Jon. I'd rather add `mkdir -p sync` to the target than add `clean` as a dependency.

**Comment by AustinAbro321** [comment]
Yeah that makes sense. I hadn't realized that more gets stored in sync than just the releases. I'll configure my git to sign commits and push that change up

**Comment by RothAndrew** [comment]
You'll need to squash with the last commit and force push (or make a new branch). We have GitHub configured to require ALL commits in a PR to be signed before it is able to merge.

**Comment by AustinAbro321** [comment]
Change is made and commits are squashed and verified. And I learned about git rebase along the way!

**Review by YrrepNoj — APPROVED** [review]

**Pull request merged**
