### PR TITLE
Working Longhorn Example

### PR DESCRIPTION
**Pull request by JasonvanBrackel**
## Description
Add to Longhorn to Zarf Examples 

## Related Issue

Relates to https://github.com/defenseunicorns/zarf/issues/854 as longhorn will be used as the backing storage for this ZarfInitPackage

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by wirewc** [comment]
Definitely should do the annotation for the service so a user may access the API.

**Comment by jeff-mccoy** [comment]
NIce, I didn't realize how big it was 😆. Can we drop a couple of screenshots of this in action since we don't have a test for it right now?

**Comment by JasonvanBrackel** [comment]
> Definitely should do the annotation for the service so a user may access the API.

I'm using the upstream helm chart, I'll have to see if there's a helm value to add the annotation.  

I'll think it through if not.

**Comment by JasonvanBrackel** [comment]
> NIce, I didn't realize how big it was 😆. Can we drop a couple of screenshots of this in action since we don't have a test for it right now?

Sure thing

**Comment by JasonvanBrackel** [comment]
Here's some screens from the twitch stream where I was working on it.
image
image
image
image

**Comment by JasonvanBrackel** [comment]
@jeff-mccoy screenshots there and @wirewc connect added

**Review by jeff-mccoy — APPROVED** [review]
great add, lgtm

**Pull request merged**
