### PR TITLE
Add Zarf Features to Docs Overview pg.

### PR DESCRIPTION
**Pull request by Madeline-UX**
## Description

Add a section on the Docs overview (home page) listing out the features of Zarf. 
- out of the box
- configurable

## Related Issue

- [ ] New feature (non-breaking change which adds functionality)

## Checklist before merging

- [x] Documentation has been updated as necessary (add the `needs-docs` label)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
We should tagup on this next week sometime, some of these features are a good fit, but I think some are too in the details and should be better summarized.

**Comment by Madeline-UX** [comment]
@jeff-mccoy Sounds great. Will plan to discuss this during Tuesday's office hours.

**Comment by Madeline-UX** [comment]
@jeff-mccoy Here is a working list of features that I have collected

📦 Out of the Box Features

- Automates Kubernetes orchestration in disconnected environements.
- Automates SBOM Generation
- UI Dashboard for viewing SBOM findings
- Deploy a cluster while fully disconnected (using K3s)
- Deploy pre-built tar.zst package onto a machine or server (specifically into a k8s cluster)
- Built in Logging
- Seed Git Registry
- Automatically update pod's ImagePullSecrets so deployed resources use the NodePort binding. See Zarf Agent.
- K9 Dashboard for visualizing containers and clusters
- Finds images and resources from helm chart
- Creates secure tunnel ports for deployments

🛠️ Configurable Features

- Manage CPU usage
- Mount onto existing cluster
- Customize packages variables

**Comment by YrrepNoj** [comment]
@Madeline-UX Do you want to tag up this sometime this week? I'd love to help get this added to the docs.

And question for whenever we have time to talk; do we want to differentiate the features of 'Zarf the CLI' and 'the released Initialization Package'? The features listed above are a mix between the two which might be confusing for some.

**Comment by jeff-mccoy** [comment]
Closing as these are covered by other PRs now.

**Review by jeff-mccoy — APPROVED** [review]

**Comment by Madeline-UX** [comment]
@jeff-mccoy Is there a reason I am not seeing the merged changes updated on the Docs overview site?

**Pull request merged**
