### PR TITLE
test: remove TestMismatchedVersions e2e test

### PR DESCRIPTION
**Pull request by lucasrod16**
## Description
Removes `TestMismatchedVersions` and adds `TestPrintBreakingChanges` unit test

## Related Issue

Relates to #2562

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/.github/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by lucasrod16** [comment]
Sharing screenshots to compare the output of `PrintBreakingChanges` before and after the refactoring in this PR

Before:

before


After:

after

**Comment by phillebaba** [comment]
Might be out of scope for this but I would much rather have PrintBreakingChanges return a string and then have the calling function output it to the correct writer. Makes things cleaner and easier to test. Other than that this looks good.

**Review by AustinAbro321 — APPROVED** [review]
Agree with Phillip, that it should be refactored but it's fine to merge now. Just make an issue for the refactoring if you merge now

**Comment by lucasrod16** [comment]
> Might be out of scope for this but I would much rather have PrintBreakingChanges return a string and then have the calling function output it to the correct writer. Makes things cleaner and easier to test. Other than that this looks good.

@phillebaba @AustinAbro321  https://github.com/defenseunicorns/zarf/issues/2570

**Pull request merged**
