### PR TITLE
fix typo in build your own zarf cli page

### PR DESCRIPTION
**Pull request by decleaver**
## Description

Fixing Typo in Dependencies section of https://docs.zarf.dev/docs/user-guide/the-zarf-cli/building-your-own-cli

## Related Issue

Typo in website

Fixes # (issue)

## Type of change

Typo in website

### CODE REVIEW

**Review by Racer159 — APPROVED** [review]
:musical_note: :musical_note: :musical_note: we built this city :musical_note: :musical_note: :musical_note: we built this city on rock and roll :musical_note: :musical_note: :musical_note:

**Comment by Racer159** [comment]
@decleaver approved, but can you go back and sign your commit? See 3) in dev workflow: https://github.com/defenseunicorns/zarf/blob/30db9cb26ee913a19930cb65d0773b51c9b8261d/CONTRIBUTING.md

**Comment by jeff-mccoy** [comment]
Wait I still see an unsigned commit, we may need you to just squash your commits first. Am I going crazy @Racer159?
Screen Shot 2022-09-26 at 11 24 39 AM

**Comment by Racer159** [comment]
You aren't crazy @jeff-mccoy .  @decleaver to squash just run: 

```
git rebase -i HEAD~<number of commits>
git push -f
```

If there are any unsigned commits in the branch they can't be merged to master.

Source: https://medium.com/iosnesia/how-to-squash-commits-in-git-e73a41248211

**Comment by Racer159** [comment]
Closing in favor of other branch

**Pull request closed without merging**
