### PR TITLE
1337 kustomize direct

### PR DESCRIPTION
**Pull request by UncleGedd**
## Description

...

## Related Issue

Fixes #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by Racer159** [comment]
Assuming this is still a Helm-related issue, can we do something like this instead (either on your side upstream or as a string literal wrapper to turn off Helm processing?)  Likely a much better way than diving into the lifecycle of Zarf:
image

**Comment by jeff-mccoy** [comment]
What issue is this related to? I have concerns about moving away from helm for anything as it's a fundamental change to how we manage k8s resources and a complexity I don't think we can take on.

**Comment by UncleGedd** [comment]
Related issue and more context/conversation: https://github.com/defenseunicorns/zarf/issues/1337

@wirewc and I discussed something similar yesterday. Either:
1. make the change my upsteam Helm chart (as @Racer159 suggests)
2. maybe use a Zarf action to do some string replacement

**Comment by Racer159** [comment]
Closing in favor of #1350

**Pull request closed without merging**
