### PR TITLE
606 generate docs from zarf schema json

### LINKED ISSUE #606: Generate docs from zarf.schema.json
**Is your feature request related to a problem? Please describe.**
It is difficult to keep docs up to date with code changes at times and generating them in some fashion from the code itself is usually a cleaner way to handle updating them.

**Describe the solution you'd like**
We can use https://github.com/adobe/jsonschema2md to generate documentation for the Zarf package schema directly from the zarf.schema.json file.

**Describe alternatives you've considered**
There are other similar plugins like https://github.com/saibotsivad/json-schema-to-markdown but the adobe one seems to work and is the most well maintained of the options I had found.

**Additional context**
Zarf is cool!

### PR DESCRIPTION
**Pull request by Racer159**
## Description

Generated markdown from zarf.schema.json to include in docs.

## Related Issue

Fixes #606 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist before merging

- [X] Tests have been added/updated as necessary (add the `needs-tests` label)
- [x] Documentation has been updated as necessary (add the `needs-docs` label)
- [X] An ADR has been written as necessary (add the `needs-adr` label) [ [1](https://github.com/joelparkerhenderson/architecture-decision-record) [2](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) [3](https://adr.github.io/) ]
- [X] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Is there a clean way to test / preview this for the docs website?  maybe create a PR with the submodule update?

**Comment by YrrepNoj** [comment]
> Is there a clean way to test / preview this for the docs website? maybe create a PR with the submodule update?

https://github.com/defenseunicorns/zarf-docs/pull/38

**Comment by Racer159** [comment]
Just made it slightly cleaner to look at (included a link to the zarf.schema.json file)

**Review by jeff-mccoy — DISMISSED** [review]
🥳

**Comment by jeff-mccoy** [comment]
Boo missed signing a commit, need that fixed to merge.  Screen Shot 2022-07-12 at 8 21 43 PM

**Comment by Racer159** [comment]
Squashed all the commits and resigned (was a lot of junk tests anyway).

**Comment by Racer159** [comment]
> Boo missed signing a commit, need that fixed to merge. Screen Shot 2022-07-12 at 8 21 43 PM
Squashed all the commits and resigned (was a lot of junk tests anyway).

**Review by jeff-mccoy — APPROVED** [review]
lgtm thx

**Pull request merged**
