### PR TITLE
Increase Gitea's CPU limit

### PR DESCRIPTION
**Pull request by RothAndrew**
## Description

Updates the CPU limit for Gitea from "1" to "10". "10" is an arbitrarily large number that doesn't mean much other than that it is likely bigger than Gitea will ever need.

[CPU limits tend to constrain resources when they don't need to be constrained](https://home.robusta.dev/blog/stop-using-cpu-limits)

Until #1122 is merged this works as a decent halfway measure that will resolve the issue of Gitea being throttled unnecessarily. It's not the final solution, but it's a net positive so we shouldn't wait for #1122 to do this.

## Related Issue

#1122

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist before merging

no new tests or docs needed. I can do a quick ADR if we feel it is needed that would address a generalized strategy for CPU limits.

### CODE REVIEW

**Comment by RothAndrew** [comment]
Screenshot demonstrating Gitea being throttled even though there was plenty of CPU on the node

image

**Comment by YrrepNoj** [comment]
I agree that the CPU limit should be increased, I also agree that a longer term solution for this is to [follow the pattern of the registry](https://github.com/defenseunicorns/zarf/blob/3de6e411b7098f083a57fdee2c6d59230a8afcf9/packages/zarf-registry/zarf.yaml#L23) and have this value be a variable that can be configured.


That being said, if we can come up with what we think the CPU Limit for Gitea should be, I think it makes perfect sense to get this PR merged in with whatever that value should be.


I recommend we use the same CPU limit we use for the container registry and set the limit to `3`.

**Comment by RothAndrew** [comment]
changed value to 3

**Comment by RothAndrew** [comment]
I'm going to wait a day or two to see if anyone that is new to development of Zarf picks up #1122 since I labeled it "good-first-issue". If nobody does I'll take care of it. I agree it is a fairly trivial change.

In the meantime, I'm not seeing any reason that this PR shouldn't merge in the interim, in accordance with the principles of DevOps best practices of making frequent small changes.

#1122 will be done as the "final" "good" solution. I'm making the argument that that should not block this from merging.

**Comment by jeff-mccoy** [comment]
@RothAndrew, I think we can close this now; I opened #1133 with a default limit of 3 CPUs. We'll include it in the next release once approved. Thoughts?

**Comment by RothAndrew** [comment]
Sounds like @gscallon picked up the issue for variables. Make sure you guys aren't doing the same work

**Comment by jeff-mccoy** [comment]
Okay, not a problem; I'll let them know we already have it covered. I wanted to get this change in before the `0.23` release. I will go ahead and close this one.

**Pull request closed without merging**
