### PR TITLE
Make GitOps E2E test more robust + minor cleanup

### PR DESCRIPTION
**Pull request by RothAndrew**
- Make GitOps E2E test more robust by using a newer tag that got created after the major force push to master
- Minor cleanup of dead code

### CODE REVIEW

**Comment by RothAndrew** [comment]
@jeff-mccoy Here's the scoped down PR for just the E2E test changes. The other one will get smaller once master gets integrated including this change

**Review by jeff-mccoy — APPROVED** [review]
Lgtm

**Comment by jeff-mccoy** [comment]
I'm a little sad you didn't stay on the dark side 😂 but 👍.

**Comment by RothAndrew** [comment]
Gotta set a good example for the younglings 😉

**Pull request merged**
