### PR TITLE
Make the agent mutate on update as well as create

### LINKED ISSUE #564: The Zarf Agent mutating webhook mutates objects on `CREATE` only, not `UPDATE`
### Environment
Device and OS: EC2 instance running Ubuntu
App version: v0.19.5
Kubernetes distro being used: K3s v1.21.6+k3s1
Other:

### Steps to reproduce
1. Deploy a Flux-based setup that uses GitRepositories, where the `url:` param uses an "upstream" url that isn't "zarf-ified"
2. Update one of the GitRepositories in your config repo and push that new commit to gitea so that flux picks it up

### Expected result

The `url:` param still specifies a "zarf-ified" URL due to a mutation from the zarf agent

### Actual Result

The `url:` param now specifies the upstream "non-zarf-ified" URL

### Visual Proof (screenshots, videos, text, etc)

image

### Severity/Priority

Medium, this is gonna cause things to break in [DI2-ME](https://github.com/defenseunicorns/zarf-package-software-factory), but it won't imminently cause a production-down event

### Additional Context

The mutating webhook for [pods](https://github.com/defenseunicorns/zarf/blob/b1cf764340a8c0210435934f2543369d94c9f4b1/packages/zarf-agent/manifests/webhook.yaml#L36) as well as [GitRepositories](https://github.com/defenseunicorns/zarf/blob/b1cf764340a8c0210435934f2543369d94c9f4b1/packages/zarf-agent/manifests/webhook.yaml#L77) specify `CREATE` as the only operation when the agent will mutate the object. It should specify both `CREATE` and `UPDATE`.

### PR DESCRIPTION
**Pull request by RothAndrew**
## Description

Make the Zarf Agent mutate objects on update as well as create

## Related Issue

Fixes #564

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist before merging

- [ ] Tests have been added/updated as necessary (add the `needs-tests` label)
- [ ] Documentation has been updated as necessary (add the `needs-docs` label)
- [ ] An ADR has been written as necessary (add the `needs-adr` label) [ [1](https://github.com/joelparkerhenderson/architecture-decision-record) [2](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) [3](https://adr.github.io/) ]
- [ ] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by RothAndrew** [comment]
Do we need a new version of the agent? This is a change to the kubernetes Yamil manifest in the in it package

**Comment by jeff-mccoy** [comment]
Yeah sorry just saw that, this should be fine as-is, thanks

**Review by jeff-mccoy — APPROVED** [review]

**Comment by RothAndrew** [comment]
Thanks! Are you planning on cutting a release with this change? It would help with my DI2-ME work.

**Comment by jeff-mccoy** [comment]
Yeah, cutting tonight, will be a patch.

**Pull request merged**
