### PR TITLE
Adding feature to exclude optional components

### PR DESCRIPTION
**Pull request by dgershman**
## Description

This adds the ability to exclude optional components while build a package.

## Related Issue

Relates to #1128 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by Noxsios** [comment]
Related to: https://github.com/defenseunicorns/zarf/pull/2211

**Comment by dgershman** [comment]
> Related to: #2211

@Noxsios do you think it makes sense to rebase (and continue rebasing) from your branch?

**Comment by Racer159** [comment]
Depending on timing we could go either way - now that we have a custom gather space it may be good to discuss options for this too - a few things have changed with `--components` since the issue was filed.

As I see it we could:

1. Proceed as is and create a separate components exclusion flag that is disconnected from the --components logic
2. Incorporate the components logic with `-` support and default support except that an empty components list would create with all components instead of just required and default.

**Comment by dgershman** [comment]
After our discussion in the gather space, decided to take a different route leveraging `flavor`.

**Pull request closed without merging**
