### PR TITLE
WIP: Configurable Script Timeout

### LINKED ISSUE #338: Configurable Script Timeout
**Is your feature request related to a problem? Please describe.**
In the big Software Factory package, the Atlassian suite and Jenkins are installed as separate components after Big Bang deploys, but they have to wait until Istio is running or they won't get sidecar injections. I have this in those components, so it will wait for Istio to be running before trying to deploy:

```yaml
    scripts:
      retry: true
      before:
        # Check to see if istiod is running before trying to deploy. If Istio is running then so is Gatekeeper. This is a poor man's version of "DependsOn" since we aren't doing real gitops yet
        - |
          test $(/usr/sbin/kubectl get pods -n istio-system -l app=istiod --field-selector=status.phase=Running -o json | ./jq -r '.items | length') -gt 0
```

The problem is that it can sometimes take a few minutes for Istio to be running and Zarf times it out at ~~2 minutes~~ 60 retries with a 2 second wait between tries which roughly equates to 2 minutes if you don't count actual processing time.

**Describe the solution you'd like**
I'd like the ability to configure the timeout, instead of it being hardcoded to 2 minutes.

**Describe alternatives you've considered**
I'm not really aware of any that would let me do this all in one package, automatically, without doing something super hacky with initcontainers or something.

### PR DESCRIPTION
**Pull request by RothAndrew**
DO NOT MERGE

NOTE: I'm not really trying to fix this right now, but I want people to see what I'm doing. In the short term I'm just increasing the number of retries from 60 to 300 so I can be unblocked on the work I'm doing with the Software Factory Zarf package.

Might fix #338 depending on what we want to do

### CODE REVIEW

**Comment by RothAndrew** [comment]
@jeff-mccoy @YrrepNoj Can I get your feedback on this? See #338 for context. The options in front of me right now are:

- Just push to get this change merged. It would immediately unblock me from getting the Software Factory package working, at the cost of the behavior of the script timeout changing from timeout at ~2 minutes to timeout at ~10 minutes.
- Work on a "real" fix, to make the timeout configurable by adding another parameter to the `scripts:` block in the `zarf.yaml` schema. I'm not very familiar with the codebase to do that so It'll take me a while to do it.
- Try to figure out how else I can have Jira, Confluence, and Jenkins wait until Istio is running before starting their deployments. I could maybe have multiple scripts, each that end successfully other than the last one, that timeout themselves before being killed at 2 minutes by Zarf. It would look something like:

```yaml
scripts:
  retry: true
  before:
    - <Spend 1.5 minutes retrying>
    - <Spend 1.5 minutes retrying>
    - <Spend 1.5 minutes retrying>
    - <Spend 1.5 minutes retrying>
    - <Spend 1.5 minutes retrying>
    - <Spend 1.5 minutes retrying>
    - <Fail if it still isn't done yet>
```

**Comment by YrrepNoj** [comment]
Instead of change the hardcoded retries from 60 to 300 for everything, what do you think of checking for some ZARF_RETRY_OVERRIDE environment variable? That way

1. It's more obvious that it's a band-aid fix and an obvious eyesore so we have more motivation to fix it
2. It doesn't change the default retries for everything else where 60 seems to be more than enough time

**Comment by jeff-mccoy** [comment]
Normally I'd say env bar would be a great band-aid but here, but the timeout I picked was totally arbitrary anyway so I don't think increasing it hurts anything.

**Comment by jeff-mccoy** [comment]
But to clarify it's not 300 retries as much as "10 minutes" for the user feedback.

**Comment by jeff-mccoy** [comment]
Might want to update the message.

**Comment by RothAndrew** [comment]
Is it though? The way I'm reading the code is that it tries 60 times, and it waits 2 seconds between each try. It doesn't look to be including the actual processing time of the script being run.

**Comment by jeff-mccoy** [comment]
Yeah that's fair we would need to switch to a better pattern with goroutine/channels to make it a real timeout.  But 300 times is poor wording compared to 10 minutes--even if it's fuzzy, most scripts zarf was designed to run this with would fail immediately each time until they didn't.  This wasn't totally what this feature was made for.

**Comment by RothAndrew** [comment]
`jq` is included in the Zarf package and `test` is a shell builtin.

**Comment by RothAndrew** [comment]
Though, now that I'm thinking about it more, `/usr/sbin/kubectl` only applies to K3s-mode, which shouldn't be expected long term

**Pull request closed without merging**
