### PR TITLE
Make init package idempotent

### PR DESCRIPTION
**Pull request by jeff-mccoy**
## Description
This PR resolves issues with re-running `zarf init` on an existing zarf cluster.  Specifically, it resolves an issue with the injector not excluding itself from the mutating webhook and also the seed registry not using persistence causing issues with upgrades.

### CODE REVIEW

**Comment by Racer159** [comment]
@jeff-mccoy @JasonvanBrackel @YrrepNoj thoughts on splitting the test for this into its own task under https://github.com/defenseunicorns/zarf/issues/774? If we get this in where we can run double inits we could add a new ci workflow for handling upgrade testing.

**Comment by jeff-mccoy** [comment]
@Racer159 I'm totally fine with that

**Comment by JasonvanBrackel** [comment]
Agree with @Racer159.  Fine with that

**Review by Racer159 — APPROVED** [review]
lgtm.  Will need https://github.com/defenseunicorns/zarf/issues/774 eventually

**Pull request merged**
