### PR TITLE
fix: remove duplicate logic for writing image layers to disk concurrently

### PR DESCRIPTION
**Pull request by lucasrod16**
## Description
remove duplicate logic for writing image layers to disk concurrently

crane does this already in `WriteImage()`:
https://github.com/defenseunicorns/zarf/blob/08c92e12a4a2b05d0ea5abe055c7c01ba9964051/src/internal/packager/images/pull.go#L342

https://github.com/google/go-containerregistry/blob/8dadbe76ff8c20d0e509406f04b7eade43baa6c1/pkg/v1/layout/write.go#L333-L340

## Type of change
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Review by AustinAbro321 — APPROVED** [review]

**Comment by Noxsios** [comment]
Looking at the BB test, there appears to be a ~2 min added to its run time.

@lucasrod16 Can you run the test locally and verify there is no slow down?

References: 

- new: https://github.com/defenseunicorns/zarf/actions/runs/8559377937/job/23456095536?pr=2409
- current: https://github.com/defenseunicorns/zarf/actions/runs/8559736041/job/23457201460?pr=2403
- another current: https://github.com/defenseunicorns/zarf/actions/runs/8559425981/job/23456238023?pr=2405

**Comment by lucasrod16** [comment]
> Looking at the BB test, there appears to be a ~2 min added to its run time.
> 
> @lucasrod16 Can you run the test locally and verify there is no slow down?
> 
> References:
> 
>     * new: https://github.com/defenseunicorns/zarf/actions/runs/8559377937/job/23456095536?pr=2409
> 
>     * current: https://github.com/defenseunicorns/zarf/actions/runs/8559736041/job/23457201460?pr=2403
> 
>     * another current: https://github.com/defenseunicorns/zarf/actions/runs/8559425981/job/23456238023?pr=2405

Measuring the performance of the changes in this PR would be more accurate by writing a benchmark test for `PullAll()`

There are a lot of other factors that play into the BB test that are not related to or impacted by the changes in this PR. For example, in the `another current` action run you mentioned, the `Run tests` step takes `5:50`, but in the `new` action run you mentioned the `Run tests` step takes `5:42`, which is faster. The reason the `new` action run was so much slower because the `Cleanup files` step took `2:24`, where it usually only takes a few seconds. Nothing in this PR affects that step though.

Here is a benchmark that can be ran for `PullAll()` to measure it more accurately:

```go
package images

import (
	"testing"

	"github.com/defenseunicorns/zarf/src/config"
	"github.com/defenseunicorns/zarf/src/pkg/transform"
)

// BenchmarkPullAll benchmarks the PullAll function.
func BenchmarkPullAll(b *testing.B) {
	config.CommonOptions.CachePath = b.TempDir()
	imageConfig := ImageConfig{
		ImagesPath: b.TempDir(),
		ImageList: []transform.Image{
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.6.1", // 1
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.6.0", // 2
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.5.4", // 3
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.5.3", // 4
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.5.2", // 5
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.5.1", // 6
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.5.0", // 7
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.4.1", // 8
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.4.0", // 9
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.6", // 10
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.5", // 11
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.4", // 12
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.3", // 13
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.2", // 14
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.1", // 15
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.3.0", // 16
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.2.3", // 17
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.2.2", // 18
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.2.1", // 19
			},
			{
				Reference: "ghcr.io/stefanprodan/podinfo:6.2.0", // 20
			},
		},
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := imageConfig.PullAll()
		if err != nil {
			b.Fatalf("Error in PullAll: %v", err)
		}
	}
}

```

benchmarks from `main`:

benchmark-main

average duration: `9.6748` seconds

benchmarks from this PR branch:

benchmark-delete-duplicate-logic

average duration: `9.4554` seconds

Performance is almost identical from my local benchmarks. This PR arguably speeds things up, but would be good to run them locally on different machines to compare.

It would probably be good to commit this benchmark to test future changes against

**Comment by lucasrod16** [comment]
Using the images in the test package `src/extensions/bigbang/test/package`:

```go
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2024-Present The Zarf Authors

// Package images provides functions for building and pushing images.
package images

import (
	"testing"

	"github.com/defenseunicorns/zarf/src/config"
	"github.com/defenseunicorns/zarf/src/pkg/transform"
)

// BenchmarkPullAll benchmarks the PullAll function.
func BenchmarkPullAll(b *testing.B) {
	config.CommonOptions.CachePath = b.TempDir()
	imageConfig := ImageConfig{
		ImagesPath: b.TempDir(),
		ImageList: []transform.Image{
			{
				Reference: "registry1.dso.mil/ironbank/fluxcd/source-controller:v1.2.4",
			},
			{
				Reference: "registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v1.2.2",
			},
			{
				Reference: "registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.37.4",
			},
			{
				Reference: "registry1.dso.mil/ironbank/fluxcd/notification-controller:v1.2.4",
			},
			{
				Reference: "registry1.dso.mil/ironbank/big-bang/base:2.1.0",
			},
			{
				Reference: "registry1.dso.mil/ironbank/twistlock/console/console:32.01.128",
			},
			{
				Reference: "registry1.dso.mil/ironbank/twistlock/defender/defender:32.01.128",
			},
		},
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, err := imageConfig.PullAll()
		if err != nil {
			b.Fatalf("Error in PullAll: %v", err)
		}
	}
}

```

benchmarks from `main`:

benchmark-main

average duration: `67.2986` seconds

benchmarks from this PR branch:

benchmark-delete-duplicate-logic

average duration: `73.179` seconds

`registry1.dso.mil` can be pretty unreliable at times, so the performance/reliability of the remote registries we're pulling from should be factored in and considered when viewing benchmark results.

**Comment by lucasrod16** [comment]
Created an issue to add a benchmark test for image pulls: https://github.com/defenseunicorns/zarf/issues/2423

**Pull request merged**
