### PR TITLE
Fix agent mutation of new registry

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This is a hotfix related to the image SHASUMs introduced recently to not mutate the zarf registry on a zarf reinit.

## Related Issue

Fixes # N/A

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist before merging

- [X] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Is there a reason we wouldn't just add the correct agent ignore label to the pod all the time vs hardcode a special exemption that would still hit the webhook?

**Comment by jeff-mccoy** [comment]
Actually thing we need to use ignore/skip "zarf.dev/agent=ignore" here instead.  Reason for this is if the agent and registry both died due to node failures, you'd be stuck in a pending state with "patched" waiting for the agent whereas ignore wouldn't depend on the agent existing at all.

**Review by jeff-mccoy — CHANGES_REQUESTED** [review]
I think we need to use ignore/skip `zarf.dev/agent=ignore` here instead. Reason for this is if the agent and registry both died due to node failures, you'd be stuck in a pending state with "patched" waiting for the agent whereas ignore wouldn't depend on the agent existing at all.

**Comment by Racer159** [comment]
> 

Changed

**Review by jeff-mccoy — APPROVED** [review]

**Pull request merged**
