### PR TITLE
Add `big-bang-umbrella` folder back to Zarf examples...

### PR DESCRIPTION
**Pull request by RothAndrew**
...with a README that redirects the reader to the new repo that replaced it

### CODE REVIEW

**Comment by RothAndrew** [comment]
Ready for review & merge

**Comment by jeff-mccoy** [comment]
@RothAndrew I'm confused on this PR a little bit, I see the readme updates and makes total sense, but "...also fix broken E2E test" seems completely unrelated to the topic PR.  Now of course I don't mind combining these as I do it all the time, but think the PR topic needs to be updated because a README change and E2E tests are very different, very unrelated things.  Thoughts?

**Comment by RothAndrew** [comment]
I can pull the test change out into its own PR. I definitely want to practice what I preach 😄

**Comment by RothAndrew** [comment]
@jeff-mccoy ready for another review

**Review by jeff-mccoy — APPROVED** [review]
🦄

**Pull request merged**
