### PR TITLE
Add Jenkins to BB Umbrella (And rename to Software Factory)

### LINKED ISSUE #272: Add Jenkins to BB Umbrella example (and rename it to "Software Factory")
To-Do:
- Add jenkins to the BB Umbrella example
- Rename the BB Umbrella example to "Software Factory" since Jenkins isn't part of BB Umbrella.

### PR DESCRIPTION
**Pull request by RothAndrew**
Closes #272 

To-Do:
- [X] Get Jenkins working outside of BB
- [X] Get Jenkins working in Istio
~~- [ ] Get Keycloak working~~

--- Stopping point, engage with user, adjust as needed

~~- [ ] Get Jenkins using Keycloak~~
- [ ] Switch to the Iron Bank version of Jenkins container
~~- [ ] Get Jenkins+Keycloak working with Network Policies & OPA Gatekeeper~~
- [ ] Fix it so it does GitOps properly
~~- [ ] Documentation on what you would do to run Keycloak in a different cluster~~
- [ ] Docs
- [ ] E2E test (?)
- [ ] ??

Edit:
Getting KeyCloak running in the same cluster as everything else turned out to have more technical issues than expected. This extra effort has been captured in issue #249 and will be completed after the PR #153 gets merged into master. Until then, this PR will introduce Jenkins to the current 'Umbrella' example.

### CODE REVIEW

**Comment by RothAndrew** [comment]
@YrrepNoj this is a branch that was branched off of your umbrella branch. Let's work in here to add keycloak and stuff as we work with @david--wright on this stuff.

**Comment by RothAndrew** [comment]
Status: Jenkins works with Istio enabled. Still need to enable other BB Core things like network policies, Gatekeeper, etc

**Comment by RothAndrew** [comment]
Status: Making some updates after rebasing from the merged Big Bang Umbrella example. Renaming the Big Bang Umbrella example to Software Factory since it includes Jenkins now which isn't part of Big Bang Umbrella.

**Comment by RothAndrew** [comment]
@YrrepNoj given the updated description, I'm thinking this can be merged, either now-ish or after just a bit more testing/cleanup. Do you agree?

**Comment by RothAndrew** [comment]
This needs to get merged before #237. It will be a huge PITA to resolve conflicts if #237 merges first. I believe it is ready to go now. I'll double check it this weekend and then ask for a review so we can merge it ~Monday

**Review by YrrepNoj — DISMISSED** [review]
Manually deployed it one last time just to made sure it works. Jenkins came up and I was able to navigate to it's initial page in the browser :)

**Review by YrrepNoj — APPROVED** [review]

**Pull request merged**
