### PR TITLE
create cache dir during zarf init if it does not exist

### LINKED ISSUE #985: Windows CLI does not create ~/.zarf-cache directory.
### Environment
Device and OS: Windows 11
App version: Zarf v0.22.2
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. Run "zarf init"

### Expected result
Zarf downloads the zarf init package C:\Users\<user>\.zarf-cache

### Actual Result
```pwsh
PS C:\Users\jason> zarf init

Saving log file to C:\Users\jason\AppData\Local\Temp\zarf-2022-11-08-10-11-55-1722182145.log

...

It seems the init package could not be found locally, but can be downloaded from
https://github.com/defenseunicorns/zarf/releases/download/v0.22.2/zarf-init-amd64-v0.22.2.tar.zst

? Do you want to download this init package? Yes
     ERROR:  Unable to create the destination file y
```

You can workaround by creating the ~/.zarf_cache directory

### Visual Proof (screenshots, videos, text, etc)
image

### PR DESCRIPTION
**Pull request by Noxsios**
## Description

Handles creation of `~/.zarf-cache` during `zarf init` if it does not exist.

## Related Issue

Fixes #985 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Think you're seeing the same doc issue as I ran into, here's what I did, feel free to steal it since this PR can go in before mine:  https://github.com/defenseunicorns/zarf/pull/848/commits/f092e3dc2f930d051a373fd6f3a104225e8b452b
Screenshot 2022-11-18 at 6 11 42 PM

**Comment by Racer159** [comment]
Dangit @brandtkeller lol

**Comment by jeff-mccoy** [comment]
want to bump this one too @Noxsios

**Comment by Noxsios** [comment]
Will close this when #1096 is closed

**Pull request closed without merging**
