### PR TITLE
netpol for bb-core

### PR DESCRIPTION
**Pull request by anoncam**
## Description

Reference #555 

modded default netpol to be local IP by default.  Network policies must be declared with intent.

## Related Issue

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist before merging

- [ ] Tests have been added/updated as necessary (add the `needs-tests` label)
- [ ] Documentation has been updated as necessary (add the `needs-docs` label)
- [ ] An ADR has been written as necessary (add the `needs-adr` label) [ [1](https://github.com/joelparkerhenderson/architecture-decision-record) [2](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) [3](https://adr.github.io/) ]
- [ ] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by RothAndrew** [comment]
Will need to test this manually, the test suite doesn't test the big bang package since it's huge.

AFAIK, when I did this the first time around, using 127.0.0.1 in these values didn't work, but happy to take another look at it.

**Comment by anoncam** [comment]
let me dig around and find other use cases where there has been a similar desire to simply not use 0.0.0.0 and we may find a sweet spot to compromise

**Comment by jeff-mccoy** [comment]
@anoncam we'd still need to validate these changes with a manual test before merging. A team member will also need to validate, but if you can provide a screenshot of BB happy with the netpol changes on this PR when you have time, that would be hepful.

**Comment by anoncam** [comment]
100%.


Yeah totally, let me verify and respond then you can review and sign

**Comment by jeff-mccoy** [comment]
Close this stale PR until the requested info is added, thanks.

**Pull request closed without merging**
