### PR TITLE
Package generation

### LINKED ISSUE #821: Package Generation for projects
**Is your feature request related to a problem? Please describe.**
In order to support OSS projects (and their maintainers) and the inclusion of Air Gap testing and validation of that project using Zarf, it would be valuable if Zarf could generate the `zarf.yaml` file based on a provided git repository containing a helm chart.

(This has other possible value - such as it relates to #513 - but I wanted to provide a specific scenario and persona to provide for initial logic.)

This logic could be a repeatable way to abstract zarf knowledge required by OSS maintainers into automation that can generate a file that can easily be consumed by end users with zarf package create. 

Ideally this could be valuable during release candidate testing - but also flow into testing of air gap in CI. 

**Describe the solution you'd like**
Execute `zarf package generate <helm chart repo git url/helm registry url>` (or similar) to begin the generation of a `zarf.yaml` file. This command would use logic such as that in `zarf prepare find-images` to find the images in the chart, and otherwise use the helm chart target to instantiate the chart required fields. 

**Describe alternatives you've considered**
None - This feature is proposed to help assist OSS projects understand air gap considerations and test/validate them without needing to be a zarf expert. 

**Additional context**
Discussions around supporting open source and the ability to test air gap in CI spurred thiis thought.

### PR DESCRIPTION
**Pull request by corang**
## Description

Adds package generation to zarf, both via human friendly wizard and automation friendly cli with flags and JSON

## Related Issue

Fixes #821 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist before merging

- [ ] Tests have been added/updated as necessary (add the `needs-tests` label)
- [ ] Documentation has been updated as necessary (add the `needs-docs` label)
- [ ] An ADR has been written as necessary (add the `needs-adr` label) [ [1](https://github.com/joelparkerhenderson/architecture-decision-record) [2](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) [3](https://adr.github.io/) ]
- [ ] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Would be great to tagup this afternoon on this PR

**Comment by jeff-mccoy** [comment]
This is still marked as draft, can we get an update @corang?

**Comment by lucasrod16** [comment]
Looks like there's some merge conflicts. Think you can rebase/resolve the conflicts to ensure your changes play nicely with the current state of Zarf? @corang

**Comment by jeff-mccoy** [comment]
Closing this PR as stale, feel free to reopen if it is picked back up.

**Pull request closed without merging**
