### PR TITLE
Feat: update bigbang and flux resources to release 1.37.0

### PR DESCRIPTION
**Pull request by brandtkeller**
Signed-off-by: brandt keller <brandt.keller@defenseunicorns.com>

## Description

Doing some Zarf and Big Bang testing for learning purposes. Proposing update to latest release `1.37.0` unless there is a reason otherwise. As a Big Bang contributor, I am interested in maintaining and updating this demo to reflect the intent and streamlining of Big Bang deployments with Zarf.

I'm aware of the decision to not introduce GitOps complexity for this demo. If that changes, I would be willing to pick that issue up.

## Related Issue

No related issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist before merging

- [ ] Tests have been added/updated as necessary (add the `needs-tests` label)
- [ ] Documentation has been updated as necessary (add the `needs-docs` label)
- [ ] An ADR has been written as necessary (add the `needs-adr` label) [ [1](https://github.com/joelparkerhenderson/architecture-decision-record) [2](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) [3](https://adr.github.io/) ]
- [ ] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
Thanks @brandtkeller, since we don't have an E2E for Big Bang right now, could you drop a screenshot of the deployed `HelmRelease` resources here for the PR and I'll approve.

**Comment by brandtkeller** [comment]
Sounds good - I will work on that shortly and maybe contemplate what a E2E test for Big Bang would look like for future iterations (potential issue for others to collaborate on?).

**Comment by brandtkeller** [comment]
Screen Shot 2022-07-12 at 8 34 50 AM

**Comment by brandtkeller** [comment]
The above was deployed with `v0.19.5`

**Review by RothAndrew — APPROVED** [review]

**Review by YrrepNoj — APPROVED** [review]

**Comment by RothAndrew** [comment]
@brandtkeller can you push an empty commit to trigger the pipeline? It should be going automatically but it isn't, maybe because the last commit is a merge commit? :shrug:

**Pull request merged**
