### PR TITLE
Fixes #893  Deploying steps indexing. 

### LINKED ISSUE #893: UI Bug - Deploying Stepper numbering
## Current ##

On the deployment page in the wizard - the stepper starts with 0 

Screen Shot 2022-10-12 at 11 55 12 AM

## Update ##

Change stepper numbering to start with 1 

Screen Shot 2022-10-12 at 11 56 55 AM

### PR DESCRIPTION
**Pull request by mike-winberry**
## Description

Fix deploy-utils createComponentStepMap step numbering. Removed unused constant POLL_TIME_MS. Added some commenting in deploy-utils.

Fixes # (issue)
#893 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by mike-winberry** [comment]
https://user-images.githubusercontent.com/86802655/195691707-9351d79a-1f27-4c6f-9f37-7a2fde67fb23.mov

**Comment by jeff-mccoy** [comment]
thanks for adding videos on these PRs @mike-winberry, super helpful.

**Review by jeff-mccoy — COMMENTED** [review]
Was the POLL_TIME_MS just old code?

**Review by Noxsios — COMMENTED** [review]
lgtm, if you wanted to make Typescript happier, change the `lets` to `const` as they do not get re-declared.

**Comment by mike-winberry** [comment]
@jeff-mccoy Yes, that was old code and for both of these @Noxsios thanks I am sorely missing my pre-commit hooks, but should be cleaned up now.

**Review by jeff-mccoy — APPROVED** [review]

**Pull request merged**
