### PR TITLE
Update Big Bang example

### LINKED ISSUE #326: Error: Unable to build the kustomization for kustomizations/bigbang
### Steps to reproduce

```sh
# Checkout master
git checkout master && git pull

# Move to examples dir
cd examples

# make sure we're fresh
make clean

# build 'zarf' and 'zarf-init.tar.zst'
make build-release

# Try to build the big-bang example
make package-example-big-bang
```

### What I saw

image

When I set `-l debug`:

image

### What I expect

The big-bang example builds successfully

### Environment

* MacOS (Intel), Zarf master branch

### PR DESCRIPTION
**Pull request by RothAndrew**
- Add missing `kustomization.yaml`

Fixes #326

### CODE REVIEW

**Comment by RothAndrew** [comment]
image

image

image

**Comment by RothAndrew** [comment]
Ready for review

**Review by jeff-mccoy — APPROVED** [review]

**Comment by RothAndrew** [comment]
Thanks @jeff-mccoy. I'm thinking we should cut v0.15.1 now. If someone checks out v0.15.0 expecting all the examples in the filesystem to work at that point in time, this one won't work.

**Pull request merged**
