### PR TITLE
Bump to Big Bang 1.57.1

### PR DESCRIPTION
**Pull request by dgershman**
## Description

This bumps up to 1.57.1 version of Big Bang on the example.

## Related Issue

N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Review by Racer159 — APPROVED** [review]
lgtm, but your base branch will need to be updated.

**Comment by dgershman** [comment]
> lgtm, but your base branch will need to be updated.

rebased

**Comment by Racer159** [comment]
Also (not going to block this PR for this) but if you wanted to it should be possible to setup a renovate job for updating BB and creating PRs automatically:

Some references:
https://docs.renovatebot.com/modules/datasource/git-tags/
https://docs.renovatebot.com/modules/manager/regex/
https://github.com/defenseunicorns/zarf/blob/main/renovate.json
- See the custom regex one that we already do for charts

**Review by Racer159 — APPROVED** [review]
lgtm

**Comment by dgershman** [comment]
> Also (not going to block this PR for this) but if you wanted to it should be possible to setup a renovate job for updating BB and creating PRs automatically:
> 
> Some references: https://docs.renovatebot.com/modules/datasource/git-tags/ https://docs.renovatebot.com/modules/manager/regex/ https://github.com/defenseunicorns/zarf/blob/main/renovate.json
> 
> * See the custom regex one that we already do for charts

I will take this on as an enhancement in a new PR.

**Review by YrrepNoj — APPROVED** [review]

**Pull request merged**
