### PR TITLE
bigbang cert update

### PR DESCRIPTION
**Pull request by dgershman**
## Description

This updates the certificate for Big Bang which expired on February 25th.

## Related Issue

No ticket was raised for this, but caught on the latest pull from `main` today.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

### CODE REVIEW

**Comment by dgershman** [comment]
This reflects a change made in the Big Bang repository here: https://repo1.dso.mil/big-bang/bigbang/-/commit/a639d4382ce5480fdb25a34fb4dfa381597eb16e

**Review by Racer159 — DISMISSED** [review]
lgtm, will need sign off from @YrrepNoj as well

**Comment by Racer159** [comment]
Also @dgershman it looks like your base branch will need updating from you prior to merge - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch There should also be a setting that lets reviewers do it as well.

**Review by YrrepNoj — APPROVED** [review]

**Review by Racer159 — APPROVED** [review]
lgtm

**Pull request merged**
