### PR TITLE
Wrap the crane command to make it easier to use with Zarf

### LINKED ISSUE #1186: Make it easier to view contents of registry
**Is your feature request related to a problem? Please describe.**
It is difficult to view the contents of the zarf docker registry.

**Describe the solution you'd like**
`zarf tools registry catalog` displays the contents of the registry with no other configuration or actions needed

**Describe alternatives you've considered**
I think this is what needs to happen?

* `zarf connect <the registry>`
* then `zarf tools registry login <the registry>`
* then `zarf tools registry catalog`

**Additional context**
image (3)

### PR DESCRIPTION
**Pull request by Racer159**
## Description

This wraps the crane command so that it is easier to use more directly with Zarf

## Related Issue

Fixes #1186 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Checklist before merging

- [X] Documentation has been updated as necessary (add the `needs-docs` label)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
This is a great short-term add, I was actually thinking maybe we should just add a more top-level command to interact with artifacts/assets zarf deploys.  Something like `zarf artifact images` or`zarf assets images`. I think it should probably be view-only since mutation would break the nature of declarative packages. Also `zarf artifact repos`. Thoughts?

**Comment by Racer159** [comment]
> 

I think that could make sense, though we would likely need to pull that info from the zarf state instead of the actual service.  Doing that for git repos might get tricky across git hosts.

**Review by jeff-mccoy — CHANGES_REQUESTED** [review]
There's a lint error in `tools.go`. Also, since we're adding custom logic outside of just crane, we should add a test for this. Fortunately we also need this function in the `src/test/e2e/21_connect_test.go` test, so might be able to just drop it in there.

**Comment by Racer159** [comment]
> There's a lint error in `tools.go`. Also, since we're adding custom logic outside of just crane, we should add a test for this. Fortunately we also need this function in the `src/test/e2e/21_connect_test.go` test, so might be able to just drop it in there.

Fixed

**Review by jeff-mccoy — APPROVED** [review]
💥

**Pull request merged**
