### PR TITLE
Update gitops-service component in init config

### PR DESCRIPTION
**Pull request by RothAndrew**
## Description

Update the name of the `gitops-service` component in the init config to `git-server`, since it now only includes a git server. 

## Related Issue

none

## Type of change

- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist before merging

- [X] Tests have been added/updated as necessary (add the `needs-tests` label)
- [X] Documentation has been updated as necessary (add the `needs-docs` label)
- [X] An ADR has been written as necessary (add the `needs-adr` label) [ [1](https://github.com/joelparkerhenderson/architecture-decision-record) [2](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions) [3](https://adr.github.io/) ]
- [X] (Optional) Changes have been linted locally with [golangci-lint](https://github.com/golangci/golangci-lint). (NOTE: We haven't turned on lint checks in the pipeline yet so linting may be hard if it shows a lot of lint errors in places that weren't touched by changes. Thus, linting is optional right now.)

### CODE REVIEW

**Comment by jeff-mccoy** [comment]
So just to understand--you're proposing we rename "gitops-service" to "gitea"?  Is there any particular reason or is this part of a larger set of changes?

**Comment by RothAndrew** [comment]
I thinks that’s about it, yeah. It started with just updating the description since gitops-service doesn’t do a registry anymore, but then I got to thinking there could be a better name for it. Gitops-service is a pain to type and since it is only GitLab it made sense to just call it gitea

**Comment by RothAndrew** [comment]
Or maybe just call it `git`? That would give us the flexibility to possibly swap out the tool in the future if we feel the need to without needing to change the component name again.

**Comment by YrrepNoj** [comment]
My preference is `git-server`

**Comment by jeff-mccoy** [comment]
> My preference is `git-server`

concur.

**Review by jeff-mccoy — APPROVED** [review]
LGTM

**Pull request merged**
